function plotAA(name, preds, alpha, gamma, epsilon, episodes, runs, state, saveDir)

fileName = strcat(name, '_Preds', num2str(preds),...
    'Alpha',num2str(alpha),...
    'Gamma',num2str(gamma),...
    'Epsilon',num2str(epsilon),...
    'Episodes',num2str(episodes),...
    'Runs',num2str(runs),...
    state);
data = importdata(strcat(fileName, '.txt'));
meanLength = data(1,:);
devLength = data(2,:);
meanEnd = data(3,:);
devEnd = data(4,:);
h = figure();
subplot(2,1,1)
plotGP(1:length(meanLength), meanLength, devLength);
title(strcat(name, ', predators=',num2str(preds),...
    ', a=',num2str(alpha),...
    ', e=',num2str(epsilon),...
    ', ',state));
xlabel('Episode');
ylabel('Episode length');
subplot(2,1,2);
plotGP(1:length(meanEnd), meanEnd, devEnd);
xlabel('Episode');
ylabel('Prey caught ratio');
saveName = strcat(saveDir, fileName, '.pdf');
saveas(h, saveName, 'pdf');
